### ISSUE TITLE
Dump files

### ISSUE THREAD

**Issue by Gerhard-Davel** [iyume/numpy-convolution-forward#1]
Hi iyume,

Where can I find the files you use to evaluate the models, i.e. the files in **"dump/..."**. Or alternatively how can I generate these files myself?

kind regards

**Comment by iyume** [comment]
You must train the VGG19 at `model/keras.py` yourself, and save its weight to `ckpt/epoch30`.

But the weight must be converted to numpy array by following code. (call `tfvar2numpy` to convert)

https://github.com/iyume/numpy-convolution-forward/blob/b483fca765d7fbba475a2134df1378f36e82b427/eval_keras.py#L18-L22

By running `eval_keras.py`, you can get `dumps/epoch30.pkl` file.

**Comment by Gerhard-Davel** [comment]
Thank you for the reply. I will give this a try.
